# Generated by Django 4.1.1 on 2023-04-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arba_app', '0002_products_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='image',
            new_name='pro_image',
        ),
        migrations.AddField(
            model_name='products',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='arba_app.categories'),
        ),
    ]
