# Generated by Django 4.1.1 on 2023-05-08 10:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arba_app', '0005_cart1'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='cat_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='cat_name', unique=True),
        ),
    ]
